import React from 'react';
import { CircleCheck, Clock3, Activity, ArrowUpRight } from 'lucide-react';
import PixelPerson from '@/components/company/PixelPerson';
import { getDepartment, statusLabels } from '@/components/company/companyData';
export default function ActivityPanel({ tasks, departmentIds, onTask, onAgents, isDemo }) {
  const recent = [...tasks].sort((a,b)=>new Date(b.updated_date || b.created_date)-new Date(a.updated_date || a.created_date)).slice(0,5);
  const done = tasks.filter(t=>t.status==='completed').length;
  return <aside className="activity-column"><section className="panel activity-panel"><div className="section-heading"><h2>최근 활동</h2><Activity size={16} color="#9693a5"/></div><div className="activity-feed">{recent.map(task=>{const d=getDepartment(task.department);return <button className="activity-item" key={task.id} onClick={()=>onTask(task)}><span className={`activity-node ${task.status==='completed' ? 'done' : ''}`}>{task.status==='completed'?<CircleCheck size={14}/>:<Clock3 size={14}/>}</span><span><small>{d.name} <span>· {task.assignee}</span></small><strong>{task.title}</strong><em>{statusLabels[task.status]} <span>· {new Date(task.updated_date || task.created_date).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</span></em></span></button>})}{!recent.length && <div className="empty-state"><Activity size={25}/><p>첫 작업을 등록하면<br/>활동이 여기에 표시돼요.</p></div>}</div><div className="feed-footer"><span className="live-dot"/>{isDemo ? '샘플 활동을 보고 있어요' : '작업 변경 시 자동 업데이트'}</div></section>
    <section className="panel team-panel"><div className="section-heading"><h2>우리 회사 팀장님</h2><span className="heading-count">{departmentIds.length}</span></div>{departmentIds.map(id=>{const d=getDepartment(id),count=tasks.filter(t=>t.department===id&&t.status==='in_progress').length;return <button key={id} className="leader-row" onClick={onAgents}><span className="leader-avatar" style={{background:d.pale}}><PixelPerson color={d.color} size={36}/></span><span><strong>{d.names[0]}<small>팀장</small></strong><em>{d.name}</em></span><span className={`leader-state ${count ? 'busy' : ''}`}><i/>{count?'업무 중':'대기'}</span></button>})}<button className="all-agents" onClick={onAgents}>에이전트 전체 보기 <ArrowUpRight size={14}/></button></section>
    <div className="summary-note"><span>ONE TASK AT A TIME</span><h3>오늘도 한 걸음 더.</h3><p>{done ? `${done}개의 작업이 완료되었어요.` : '첫 번째 성과를 만들어 보세요.'}<br/>작은 실행이 큰 성장을 만들어요.</p><div className="note-art"><PixelPerson size={51} color="#8870c6"/><span>✦</span><PixelPerson size={42} variant={2} color="#8eae95"/></div></div>
  </aside>;
}