import React, { useState } from 'react';
import { Building2, LoaderCircle } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { initialDepartments, getDepartment } from '@/components/company/companyData';
export default function SetupDialog({ open, onClose, company, isDemo, onSave }) {
  const [name,setName]=useState(isDemo?'':company?.name || ''), [type,setType]=useState(company?.business_type || 'IT · 소프트웨어'), [busy,setBusy]=useState(false), [error,setError]=useState('');
  const ids=isDemo?initialDepartments(type):company?.departments || [];
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{await onSave({name:name.trim(),business_type:type});onClose();}catch(err){setError(err.message || '설정을 저장하지 못했습니다.');}finally{setBusy(false);}}
  return <Dialog open={open} onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="company-dialog"><DialogHeader><span className="dialog-feature-icon"><Building2 size={24}/></span><DialogTitle>{isDemo?'대표님의 회사를 시작해 볼까요?':'회사 설정'}</DialogTitle><DialogDescription>{isDemo?'회사에 맞는 부서와 픽셀 직원들을 준비해 드릴게요.':'회사의 이름과 비즈니스 정보를 관리하세요.'}</DialogDescription></DialogHeader><form onSubmit={submit} className="company-form"><label>회사 이름<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="예: 픽셀 스튜디오"/></label><label>비즈니스 종류<select value={type} onChange={e=>setType(e.target.value)}><option>IT · 소프트웨어</option><option>마케팅 · 에이전시</option><option>컨설팅 · 전문 서비스</option><option>기타</option></select></label><div className="setup-preview"><strong>{isDemo?'자동으로 구성될 우리 팀':'현재 부서 구성'}</strong><div>{ids.map(id=><span key={id}>{getDepartment(id).name}</span>)}</div><p>부서마다 팀장 1명 + 팀원 3명 · 총 {ids.length*4}명{!isDemo && ' (기존 부서는 유지됩니다)'}</p></div><p className="form-notice">{isDemo?'샘플 작업은 가져오지 않고 빈 작업 목록으로 시작해요. ':''}외부 서비스는 아직 연결되지 않았으며, 작업 상태는 직접 관리할 수 있어요.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary-button full-width" disabled={busy||!name.trim()}>{busy?<LoaderCircle size={17} className="animate-spin"/>:<Building2 size={17}/>} {busy?'저장 중…':isDemo?'내 회사 만들기':'변경사항 저장'}</button></form></DialogContent></Dialog>;
}