import React, { useState } from 'react';
import { LoaderCircle, ListTodo } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { getDepartment, statusLabels } from '@/components/company/companyData';
export default function TaskDialog({ task, onClose, onSave, isDemo }) {
  const [status,setStatus]=useState(task.status),[progress,setProgress]=useState(task.progress || 0),[result,setResult]=useState(task.result || ''),[assignee,setAssignee]=useState(task.assignee),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const d=getDepartment(task.department);
  function changeStatus(value){setStatus(value);setProgress(value==='completed'?100:value==='queued'?0:Math.max(1,Math.min(progress,99)));}
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{await onSave(task.id,{status,progress:status==='completed'?100:status==='queued'?0:Number(progress),result,assignee});onClose();}catch(err){setError(err.message || '작업을 저장하지 못했습니다.');}finally{setBusy(false);}}
  return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="company-dialog task-detail-dialog"><DialogHeader><span className="dialog-feature-icon" style={{color:d.color,background:d.pale}}><ListTodo size={24}/></span><DialogTitle>{task.title}</DialogTitle><DialogDescription>{d.name} · {task.priority==='high'?'높은 우선순위':'보통 우선순위'} · {new Date(task.created_date).toLocaleDateString('ko-KR')}</DialogDescription></DialogHeader><p className="task-description">{task.description}</p><form className="company-form" onSubmit={submit}><div className="form-columns"><label>작업 상태<select value={status} onChange={e=>changeStatus(e.target.value)}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>담당 에이전트<select value={assignee} onChange={e=>setAssignee(e.target.value)}>{d.names.map((name,i)=><option key={name} value={name}>{name} · {d.roles[i]}</option>)}</select></label></div><label>진행률 <span>{progress}%</span><input type="range" min="1" max="99" value={progress} disabled={status!=='in_progress'} onChange={e=>setProgress(Number(e.target.value))}/></label><label>작업 메모 및 결과<textarea rows={4} value={result} maxLength={10000} onChange={e=>setResult(e.target.value)} placeholder="진행 상황 또는 완료 결과를 기록해 주세요."/></label><p className="form-notice">{isDemo?'샘플 작업입니다. 변경사항은 새로고침하면 초기화돼요.':'상태와 결과를 직접 기록하는 작업입니다. 외부 서비스에서 자동으로 실행되거나 확인된 결과가 아닙니다.'}</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary-button full-width" disabled={busy}>{busy&&<LoaderCircle size={16} className="animate-spin"/>}{busy?'저장 중…':'작업 업데이트'}</button></form></DialogContent></Dialog>;
}