import React, { useState } from 'react';
import { Search, ArrowUpRight, Inbox, ChevronDown } from 'lucide-react';
import { getDepartment, statusLabels } from '@/components/company/companyData';
import PixelPerson from '@/components/company/PixelPerson';
export default function TaskTable({ tasks, onSelect, departmentIds, compact = false, onAll, initialDepartment = 'all' }) {
  const [status, setStatus] = useState('all'), [department, setDepartment] = useState(initialDepartment), [search, setSearch] = useState('');
  const filtered = tasks.filter(t => (status === 'all' || t.status === status) && (department === 'all' || t.department === department) && t.title.toLowerCase().includes(search.toLowerCase()));
  return <section className="panel tasks-panel"><div className="section-heading"><div><h2>{compact ? '최근 작업' : '작업 목록'}<span className="heading-count">{tasks.length}</span></h2>{!compact && <p>업무를 선택해 상세 내용과 진행 상태를 관리하세요.</p>}</div>{compact && <button className="text-button" onClick={onAll}>전체 보기 <ArrowUpRight size={14}/></button>}</div>
    <div className="task-toolbar"><div className="status-tabs">{[['all','전체'],['in_progress','진행 중'],['queued','대기 중'],['completed','완료']].map(([v,l])=><button key={v} onClick={()=>setStatus(v)} className={status === v ? 'selected' : ''}>{l}</button>)}</div><div className="table-filters">{!compact && <label className="search-field"><Search size={15}/><input aria-label="작업 검색" placeholder="작업 검색" value={search} onChange={e=>setSearch(e.target.value)}/></label>}<label className="filter-select"><select aria-label="부서 필터" value={department} onChange={e=>setDepartment(e.target.value)}><option value="all">모든 부서</option>{departmentIds.map(id=><option key={id} value={id}>{getDepartment(id).name}</option>)}</select><ChevronDown size={13}/></label></div></div>
    <div className="table-scroll"><table className="task-table"><thead><tr><th>작업명</th><th>담당 부서</th><th>상태</th><th>진행률</th><th>담당자</th></tr></thead><tbody>{filtered.slice(0,compact ? 4 : filtered.length).map(task=>{const d=getDepartment(task.department);return <tr key={task.id}><td><button className="task-title" onClick={()=>onSelect(task)}><span className={`priority-dot ${task.priority === 'high' ? 'high' : ''}`}/>{task.title}</button></td><td><span className="department-tag" style={{color:d.color,background:d.pale}}>{d.name}</span></td><td><span className={`status-tag ${task.status}`}><i/>{statusLabels[task.status]}</span></td><td><span className="table-progress"><span><i style={{width:`${task.progress || 0}%`}}/></span><small>{task.progress || 0}%</small></span></td><td><span className="assignee"><PixelPerson size={24} color={d.color} variant={Math.max(0,d.names.indexOf(task.assignee))}/>{task.assignee}</span></td></tr>})}</tbody></table></div>
    {!filtered.length && <div className="empty-state"><Inbox size={28}/><strong>표시할 작업이 없어요</strong><p>아래 지시창에 첫 업무를 입력하거나 필터를 변경해 주세요.</p></div>}
    {!compact && tasks.length === 500 && <p className="table-limit">최근 500건의 작업을 표시합니다.</p>}
  </section>;
}